//! The `Tool` trait — the uniform interface every tool implements (task CB-002).
//!
//! A tool provides its name, a human/LLM-readable description, the JSON Schema
//! for its arguments, an async `execute` entry point, and an optional
//! `execute_streaming` for incremental output (CB-006).
//!
//! The trait is object-safe so tools can be stored as `Arc<dyn Tool>` inside
//! the `ToolRegistry` (CB-001) and dispatched by name at runtime.

use async_trait::async_trait;
use schemars::schema::RootSchema;
use tokio::sync::mpsc;

use super::error::ToolResult;

/// A single tool that the agent can invoke.
///
/// Implementors normally only need to provide `name`, `description`,
/// `parameters_schema`, and `execute`. The streaming variant has a default
/// implementation that simply runs `execute` and sends the full result as a
/// single message — override it for tools that can produce output line-by-line
/// (e.g. shell commands).
#[async_trait]
pub trait Tool: Send + Sync {
    /// Stable identifier used in tool-call envelopes and dispatch lookups.
    fn name(&self) -> &str;

    /// Short human-readable description. Embedded in the system prompt
    /// (CB-010) so the model knows when to call this tool.
    fn description(&self) -> &str;

    /// JSON Schema describing the tool's argument object. Generated by
    /// `schemars` from a per-tool `Args` struct (CB-003).
    fn parameters_schema(&self) -> RootSchema;

    /// Execute the tool with already-validated JSON arguments.
    ///
    /// The default contract is: the registry has already checked that `args`
    /// matches `parameters_schema()` and deserializes cleanly into the tool's
    /// own `Args` type. Implementations are free to re-deserialize as needed.
    async fn execute(&self, args: &serde_json::Value) -> ToolResult<String>;

    /// Streaming variant (CB-006).
    ///
    /// Push incremental output chunks to `tx`. The default implementation
    /// runs `execute` and sends the entire result in a single chunk, which
    /// is correct (just non-incremental) for tools like `read_file`.
    async fn execute_streaming(
        &self,
        args: &serde_json::Value,
        tx: mpsc::Sender<String>,
    ) -> ToolResult<()> {
        let out = self.execute(args).await?;
        let _ = tx.send(out).await;
        Ok(())
    }
}

/// Lightweight description used for prompt generation (CB-010) and for
/// serialising the tool list back to OpenAI-style `tools` payloads.
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub parameters: RootSchema,
}

impl ToolDefinition {
    pub fn from_tool(t: &dyn Tool) -> Self {
        Self {
            name: t.name().to_string(),
            description: t.description().to_string(),
            parameters: t.parameters_schema(),
        }
    }
}
